"use strict";

module.exports = {
  "extends": "stylelint-config-standard",
  "rules": {
    "at-rule-empty-line-before": null,
    "at-rule-name-space-after": "always",
    "at-rule-no-unknown": true,
    "at-rule-no-vendor-prefix": true,
    "block-closing-brace-newline-after": null,
    "block-closing-brace-newline-before": "always",
    "block-closing-brace-space-before": null,
    "block-closing-brace-newline-before": "always",
    "block-opening-brace-newline-after": "always",
    "color-named": "never",
    "comment-empty-line-before": null,
    "comment-no-empty": true,
    "custom-property-empty-line-before": null,
    "custom-property-no-outside-root": true,
    "declaration-bang-space-after": null,
    "declaration-bang-space-before": null,
    "declaration-block-no-duplicate-properties": [true, {
      "ignore": ["consecutive-duplicates"]
    }],
    "declaration-block-semicolon-newline-after": "always",
    "declaration-block-semicolon-space-after": null,
    "declaration-block-semicolon-space-before": null,
    "declaration-colon-newline-after": null,
    "declaration-colon-space-after": "always",
    "declaration-empty-line-before": "never",
    "font-family-name-quotes": "always-unless-keyword",
    "font-weight-notation": "numeric",
    "function-comma-newline-after": null,
    "function-comma-space-after": null,
    "function-comma-space-before": null,
    "function-parentheses-newline-inside": "never-multi-line",
    "function-parentheses-space-inside": "never",
    "function-url-no-scheme-relative": true,
    "function-url-quotes": "always",
    "indentation": 2|"tab",
    "keyframe-declaration-no-important": null,
    "max-empty-lines": 2,
    "media-feature-no-missing-punctuation": true,
    "media-query-list-comma-newline-after": null,
    "media-query-list-comma-space-after": "always",
    "no-missing-end-of-source-newline": true,
    "no-unknown-animations": true,
    "number-leading-zero": "never",
    "rule-empty-line-before": "never-multi-line",
    "property-no-unknown": null,
    "rule-empty-line-before": null,
    "selector-attribute-operator-space-after": null,
    "selector-attribute-operator-space-before": null,
    "selector-attribute-quotes": "always",
    "selector-list-comma-newline-after": null,
    "selector-list-comma-newline-before": "never-multi-line",
    "selector-no-empty": true,
    "selector-pseudo-element-colon-notation": "single",
    "selector-root-no-composition": true,
    "string-quotes": "double",
    "stylelint-disable-reason": "always-after",
    "value-keyword-case": "lower",
    "value-list-comma-newline-after": null,
    "value-list-comma-space-before": null
  }
};
